### ISSUE TITLE
Onboard Devices Programmatically

### ISSUE THREAD

**Issue by edurguti** [ciscomanagedservices/sxo-cdo#1]
Hi, is there documentation on the REST API somewhere? I am looking to onboard the FTDs programmatically using the serial number (or any other methods). At least to get them into the registered offline state, once they come online they can be onboarded using low-touch provisioning.

**Comment by sardanaaman** [comment]
Hey! There's no public documentation for the REST API I'm afraid. As far as I can tell, the [public API](https://edge.us.cdo.cisco.com/api-explorer/playground-samples) (GraphQL based) only supports querying, updating & deleting devices at the moment. I'm not in a position to comment on if/when a method to create devices will be supported. 

However, the CDO GUI uses the REST API so you could always inspect the network calls your browser makes as you navigate through the process of onboarding a device manually via the GUI and then replicate those requests with code/SecureX Orchestration. 

For instance, to onboard an FTD using the serial number, I'm seeing a `POST` made to https://www.defenseorchestrator.com/aegis/rest/v1/services/targets/devices with the payload:

```json
{
    "type": "devices",
    "deviceType": "FTD",
    "name": "<device_name_here>",
    "serial": "<device_serial_here>",
    "sseDeviceSerialNumberRegistration": {
        "sudiSerialNumber": "<device_serial_here>",
        "initialProvisionData": ""
    },
    "model": false,
    "state": "NEW",
    "tags": {},
    "sseEnabled": true,
    "ipv4": null,
    "larType": "CDG"
}
```

There are a few other `GET`s that retrieve additional context. I know this isn't the most convenient method but with a bit of experimentation, you can automate pretty much anything you can do via the GUI. Let me know if you need additional help. Thanks!

**Comment by edurguti** [comment]
Thank you! Was able to figure this out from your tips.
